### ISSUE TITLE
Help modifying python library communication protocols

### ISSUE THREAD

**Issue by rostar99** [rrooggiieerr/xyscreens.py#1]
I have a ScreenPro motorized ALR screen I would like to control via the RS485 interface. The communication protocol is similar to XYScreens but differ slightly in the commands. Rather than reinvent the wheel could I just modify my personal copy of the library to make the change. Here is the information on the RS485/RS232 protocol for ScreenPro. 

<img width="244" alt="RS485 protocol" src="https://github.com/rrooggiieerr/xyscreens.py/assets/49513347/913b90b7-b952-410e-aaed-bd398c3f12cf">
<img width="243" alt="RS485 wiring" src="https://github.com/rrooggiieerr/xyscreens.py/assets/49513347/92152aa7-4c8b-42d4-a054-fb04212afa29">

**Comment by rrooggiieerr** [comment]
Those commands look suspiciously similar to the XY Screens commands. Have you actually tried to us the library? It might just work

**Comment by rostar99** [comment]
rrooggiieerr,
I have not hung the screen yet but they are different by one element (ee instead of aa). Once I get it set up with the esp32 to control with Home Assistant I can try it to see if its close enough. If not can I just edit the library element with the altered command?

Thank you
________________________________

**Comment by rrooggiieerr** [comment]
I did some more Googling and found out your screen is developed by an OEM manufacturer named See Max.

This document of an other screen using the same commands also has some more commands to do micro movements.
https://downloads.monoprice.com/files/manuals/7951_Manual_180305.pdf

This document describes how to change the address (the middle 3 bytes) of the screen so it's possible to connect multiple screens on the same RS485 cable.
https://avaustralia.com.au/product_images/pdf/grandview/Grandview_GRPL_Lift_Manual_1014.pdf

I'm not home this week but like to try of some of these commands also work on my screen and modify the library accordingly.

You can just edit the library with the altered command and try if that works for you,

**Comment by rrooggiieerr** [comment]
FYI, I've added support for selecting device addresses and the micro movement commands the See Max OEM devices support. Your ScreenPro device should now be supported
